---
title: "Estimate Rt from incident hospitalizations"
output: html_notebook
---

Katie Gostic
```{r asis = T}
cat(sprintf('\n## Last run %s', Sys.Date()))
```


```{r echo=FALSE}
rm(list = ls())
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(cowplot)
library(EpiEstim)
theme_set(theme_bw())
knitr::opts_chunk$set(message = FALSE)
source('../code/util.R')
source('../code/cori.R')
```


## Load data
```{r}
dat <- read_csv('../data/idph_linelist_timeseries.csv') %>%
  filter(restore_region != 'unknown')
dat %>%
  ggplot()+
  geom_line(aes(x = date, y = new_deaths))+
  facet_wrap(.~restore_region, scales = 'free_y')
```

## Estimate Rt by region
```{r}
rt_by_region <- function(rr){
  
  ins <- filter(dat, restore_region == rr) %>% 
    arrange(date) %>%
    mutate(time = 1:nrow(.))
  
  ww = floor(50/max(1, quantile(filter(ins, new_deaths>0)$new_deaths, .2)))
  cat(sprintf('\nregion is %s, window is %.0f\n', rr, ww))
  
  merge(
    ins,
    get_cori(ins, 
             obs_col_name = 'new_deaths', 
             window = ww, 
             out_name = 'rt',
             mean_delay = 15, 
             SI_mean = 4.5, ## Rough estimates from Ganyani et al
             SI_var = 1.7,   
             wend = F),
    by = 'time'
  ) %>%
    select(-time) %>%
    mutate(window = ww)
}

regional_estimates <-
  bind_rows(
    lapply(unique(dat$restore_region), FUN = rt_by_region)
  )
```

## Plot
```{r}
regional_estimates %>%
  ggplot()+
  geom_line(aes(x = date, y = rt.mean, color = window))+
  geom_ribbon(aes(x = date, ymin = rt.025, ymax = rt.975), alpha = .3)+
  facet_wrap(.~restore_region) +
  ylab('Rt') +
  scale_color_viridis_c() +
  geom_vline(aes(xintercept = as.Date(max(dat$date))), lty = 2)+
  xlim(c(as.Date(min(dat$date)), as.Date(max(dat$date))))
ggsave(width = 7, height = 5, filename = sprintf('../figs/%s-regional_rt_from_idph_deaths.png', Sys.Date()), dpi = 300)
```

## Estimate Rt overall
```{r}
rt_overall <- function(dat){
  
  ins <- dat %>%
    group_by(date) %>%
    summarise(new_deaths = sum(new_deaths)) %>%
    arrange(date) %>%
    mutate(time = 1:nrow(.))
  
  ww = floor(50/max(1, quantile(filter(ins, new_deaths>0)$new_deaths, .2)))
  cat(sprintf('\noverall window is %.0f\n', ww))
  
  merge(
    ins,
    get_cori(ins, 
             obs_col_name = 'new_deaths', 
             window = ww, 
             out_name = 'rt',
             mean_delay = 15, 
             SI_mean = 4.5, ## Rough estimates from Ganyani et al
             SI_var = 1.7,   
             wend = F),
    by = 'time'
  ) %>%
    select(-time) %>%
    mutate(window = ww)
}

overall_estimates <- rt_overall(dat)
```

## Plot
```{r}
overall_estimates %>%
  ggplot()+
  geom_line(aes(x = date, y = rt.mean, color = window))+
  geom_ribbon(aes(x = date, ymin = rt.025, ymax = rt.975), alpha = .3)+
  ylab('Rt') +
  scale_color_viridis_c() +
  geom_vline(aes(xintercept = as.Date(max(dat$date))), lty = 2)+
  xlim(c(as.Date(min(dat$date)), as.Date(max(dat$date)))) +
  ggtitle('Illinois overall')
ggsave(width = 4, height = 3, filename = sprintf('../figs/%s-Illinois_rt_from_idph_deaths.png', Sys.Date()), dpi = 300)
```

